; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "GLaSSIST"
#define MyAppVersion "3.0.0"
#define MyAppPublisher "Patryk Smoliński"
#define MyAppURL "https://github.com/SmolinskiP/GLaSSIST"
#define MyAppExeName "GLaSSIST.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{27F7CD5A-57D7-4619-B622-C4D05496FD82}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=E:\GLaSSIST\LICENSE.txt
InfoBeforeFile=E:\GLaSSIST\pre-install-info.txt
InfoAfterFile=E:\GLaSSIST\post-install-info.txt
PrivilegesRequired=lowest
OutputDir=E:\GLaSSIST\inno
OutputBaseFilename=GLaSSIST-Setup
SetupIconFile=E:\GLaSSIST\img\icon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "autostart"; Description: "Start GLaSSIST automatically when Windows starts"; GroupDescription: "Startup Options"

[Dirs]
Name: "{app}"; Permissions: users-modify
Name: "{userappdata}\GLaSSIST"; Permissions: users-modify

[Files]
Source: "E:\GLaSSIST\dist\GLaSSIST\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\GLaSSIST\dist\GLaSSIST\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\GLaSSIST\.env.example"; DestDir: "{userappdata}\GLaSSIST"; DestName: ".env.example"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "GLaSSIST"; ValueData: "{app}\{#MyAppExeName}"; Tasks: autostart; Flags: uninsdeletevalue

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "https://github.com/SmolinskiP/GLaSSIST"; Description: "🐙 Visit GitHub Repository"; Flags: shellexec skipifsilent postinstall unchecked
Filename: "https://buymeacoffee.com/smolinskip"; Description: "☕ Buy Developer a Coffee"; Flags: shellexec skipifsilent postinstall unchecked

[Code]
var
  ModePage: TInputOptionWizardPage;
  HAHostPage: TInputQueryWizardPage;
  HATokenPage: TInputQueryWizardPage;
  ESPHomeDevicePage: TInputQueryWizardPage;
  ESPHomeHACredsPage: TInputQueryWizardPage;

procedure InitializeWizard;
begin
  // Step 1: Connection mode selection
  ModePage := CreateInputOptionPage(wpSelectTasks,
    'Connection Mode', 'How will GLaSSIST connect to Home Assistant?',
    'WEBSOCKET (legacy mode):' + #13#10 +
    '  • GLaSSIST initiates the connection to HA using your server address and token.' + #13#10 +
    '  • Works remotely — even outside your local network (Nabu Casa, reverse proxy).' + #13#10 +
    '  • Basic voice commands only. No timers, no conversation follow-up.' + #13#10 +
    '  • Requires a Long-Lived Access Token.' + #13#10 +
    '' + #13#10 +
    'ESPHOME SATELLITE (recommended):' + #13#10 +
    '  • HA discovers GLaSSIST automatically via mDNS (no token needed).' + #13#10 +
    '  • Full feature set: timers, shopping lists, start_conversation support.' + #13#10 +
    '  • Requires HA 2024.6+ and Voice Satellites. Local network only.' + #13#10 +
    '  • After install: Settings → Devices & Services → Add Integration → ESPHome.',
    True, False);
  ModePage.Add('WebSocket  (legacy — works remotely, basic features only)');
  ModePage.Add('ESPHome Satellite  (recommended — full features, local network)');
  ModePage.Values[0] := True;

  // Step 2a: WebSocket — HA address
  HAHostPage := CreateInputQueryPage(ModePage.ID,
    'Home Assistant Configuration', 'Enter your Home Assistant server address',
    'Please enter your Home Assistant server address without http:// or https://' + #13#10 + #13#10 +
    'Examples:' + #13#10 +
    '  Local:       192.168.1.100:8123  or  homeassistant.local:8123' + #13#10 +
    '  Nabu Casa:   yourlonglink.ui.nabu.casa' + #13#10 +
    '  DuckDNS:     myhome.duckdns.org:8123');
  HAHostPage.Add('Server Address (no http/https):', False);

  // Step 2b: WebSocket — HA token
  HATokenPage := CreateInputQueryPage(HAHostPage.ID,
    'Access Token', 'Home Assistant Authentication',
    'Enter your long-lived access token from Home Assistant:' + #13#10 + #13#10 +
    'HOW TO GET ACCESS TOKEN:' + #13#10 +
    '1. Open Home Assistant → Profile (your name, bottom left) → Security' + #13#10 +
    '2. Scroll to "Long-Lived Access Tokens" section' + #13#10 +
    '3. Click "CREATE TOKEN", name it "GLaSSIST Desktop"' + #13#10 +
    '4. Copy the token and paste below' + #13#10 + #13#10 +
    '⚠️  Keep this token secure - treat it like a password!');
  HATokenPage.Add('Long-Lived Access Token:', True);

  // Step 3: ESPHome — device settings
  ESPHomeDevicePage := CreateInputQueryPage(HATokenPage.ID,
    'ESPHome Satellite Configuration', 'Device identity in Home Assistant',
    'Configure how GLaSSIST appears in Home Assistant:' + #13#10 + #13#10 +
    'After installation, add the device in Home Assistant:' + #13#10 +
    '  Settings → Devices & Services → Add Integration → ESPHome' + #13#10 +
    '  Enter this PC''s IP address and the port below.' + #13#10 + #13#10 +
    'GLaSSIST will be auto-discovered via mDNS if your network supports it.');
  ESPHomeDevicePage.Add('Device Name (shown in HA):', False);
  ESPHomeDevicePage.Add('Port (default: 6053):', False);
  ESPHomeDevicePage.Values[0] := 'GLaSSIST';
  ESPHomeDevicePage.Values[1] := '6053';

  // Step 4: ESPHome — optional HA credentials (for media player volume control)
  ESPHomeHACredsPage := CreateInputQueryPage(ESPHomeDevicePage.ID,
    'Optional: Media Player Volume Control', 'Home Assistant credentials (optional)',
    'GLaSSIST can automatically lower the volume of your media players (speakers, TVs)' + #13#10 +
    'while you speak and restore it after the response.' + #13#10 + #13#10 +
    'This feature requires a connection to Home Assistant.' + #13#10 +
    'Leave both fields empty to skip — you can configure this later in Settings.' + #13#10 + #13#10 +
    'HOW TO GET AN ACCESS TOKEN:' + #13#10 +
    '1. Open Home Assistant → Profile (your name, bottom left) → Security' + #13#10 +
    '2. Scroll to "Long-Lived Access Tokens"' + #13#10 +
    '3. Click "CREATE TOKEN", name it "GLaSSIST Desktop"' + #13#10 +
    '4. Copy the token and paste below');
  ESPHomeHACredsPage.Add('HA Server Address (e.g. 192.168.1.100:8123):', False);
  ESPHomeHACredsPage.Add('Long-Lived Access Token (optional):', True);
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  // WebSocket pages — skip when ESPHome mode selected
  if (PageID = HAHostPage.ID) or (PageID = HATokenPage.ID) then
    Result := ModePage.Values[1];
  // ESPHome-only pages — skip when WebSocket mode selected
  if (PageID = ESPHomeDevicePage.ID) or (PageID = ESPHomeHACredsPage.ID) then
    Result := ModePage.Values[0];
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  EnvContent: string;
  EnvPath: string;
  EnvDir: string;
  ConnectionMode: string;
  DeviceName: string;
  ESPHomePort: string;
  HAHost: string;
  HAToken: string;
begin
  if CurStep = ssPostInstall then begin
    EnvDir := ExpandConstant('{localappdata}\GLaSSIST\_internal');
    EnvPath := EnvDir + '\.env';

    if not DirExists(EnvDir) then
      CreateDir(EnvDir);

    // Determine mode
    if ModePage.Values[0] then begin
      ConnectionMode := 'websocket';
      HAHost := HAHostPage.Values[0];
      HAToken := HATokenPage.Values[0];
    end else begin
      ConnectionMode := 'esphome';
      HAHost := ESPHomeHACredsPage.Values[0];
      HAToken := ESPHomeHACredsPage.Values[1];
    end;

    DeviceName := ESPHomeDevicePage.Values[0];
    if DeviceName = '' then DeviceName := 'GLaSSIST';
    ESPHomePort := ESPHomeDevicePage.Values[1];
    if ESPHomePort = '' then ESPHomePort := '6053';

    // Build .env
    EnvContent :=
      '# === CONNECTION ===' + #13#10 +
      'CONNECTION_MODE=' + ConnectionMode + #13#10 +
      'HA_HOST=' + HAHost + #13#10 +
      'HA_TOKEN=' + HAToken + #13#10 +
      'HA_PIPELINE_ID=' + #13#10 +
      '' + #13#10 +
      '# === ESPHOME SATELLITE MODE ===' + #13#10 +
      'DEVICE_NAME=' + DeviceName + #13#10 +
      'ESPHOME_PORT=' + ESPHomePort + #13#10 +
      '' + #13#10 +
      '# === ACTIVATION ===' + #13#10 +
      'HA_HOTKEY=ctrl+shift+g' + #13#10 +
      '' + #13#10 +
      '# === AUDIO ===' + #13#10 +
      'HA_SAMPLE_RATE=16000' + #13#10 +
      'HA_CHANNELS=1' + #13#10 +
      'HA_FRAME_DURATION_MS=30' + #13#10 +
      'HA_PADDING_MS=300' + #13#10 +
      'HA_MICROPHONE_INDEX=-1' + #13#10 +
      'HA_OUTPUT_DEVICE_INDEX=-1' + #13#10 +
      'HA_OUTPUT_SAMPLE_RATE=-1' + #13#10 +
      '' + #13#10 +
      '# === VOICE DETECTION (VAD) ===' + #13#10 +
      'HA_VAD_MODE=3' + #13#10 +
      'HA_SILENCE_THRESHOLD_SEC=1.5' + #13#10 +
      '' + #13#10 +
      '# === INTERFACE & PERFORMANCE ===' + #13#10 +
      'HA_ANIMATIONS_ENABLED=true' + #13#10 +
      'HA_RESPONSE_TEXT_ENABLED=false' + #13#10 +
      '' + #13#10 +
      '# === NETWORK ===' + #13#10 +
      'ANIMATION_PORT=8765' + #13#10 +
      '' + #13#10 +
      '# === AUDIO FEEDBACK ===' + #13#10 +
      'HA_SOUND_FEEDBACK=true' + #13#10 +
      'HA_CONTINUE_ON_QUESTION=false' + #13#10 +
      '' + #13#10 +
      '# === WAKE WORD DETECTION ===' + #13#10 +
      'HA_WAKE_WORD_ENABLED=true' + #13#10 +
      'HA_WAKE_WORD_MODELS=glados,alexa,computer_v2' + #13#10 +
      'HA_WAKE_WORD_THRESHOLD=0.5' + #13#10 +
      'HA_WAKE_WORD_VAD_THRESHOLD=0.3' + #13#10 +
      'HA_WAKE_WORD_NOISE_SUPPRESSION=false' + #13#10 +
      '' + #13#10 +
      '# === MEDIA PLAYER VOLUME MANAGEMENT ===' + #13#10 +
      'HA_MEDIA_PLAYER_ENTITIES=' + #13#10 +
      'HA_MEDIA_PLAYER_TARGET_VOLUME=0.3' + #13#10 +
      '' + #13#10 +
      '# === DEBUG ===' + #13#10 +
      'DEBUG=false';

    // WebSocket: save only when address + token provided
    // ESPHome: always save (HA credentials are optional — only needed for media player control)
    if ModePage.Values[0] then begin
      if (HAHost <> '') and (HAToken <> '') then
        SaveStringToFile(EnvPath, EnvContent, False);
    end else begin
      SaveStringToFile(EnvPath, EnvContent, False);
    end;
  end;
end;